### ISSUE TITLE
Code for loading pre-existing stem

### ISSUE THREAD

**Issue by jakew42** [jakew42/SelfBoostingNetworksOLD#11]
Add capability to specify a stem, load weights, and freeze them. Allows for set ups such as using a pre-trained resnet or googlenet as the stem of the model.

**Comment by DrKwint** [comment]
[Keras pre-trained models](https://keras.io/applications/#inceptionv3) would be convenient for this task, but unfortunately they are only pre-trained on ImageNet. Is that a direction we'd be willing to move in?
